/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Aluno;
import fatec.poo.model.Pessoa;
import java.util.ArrayList;

/**
 *
 * @author Bley
 */
public class GuiAluno extends javax.swing.JFrame {

    /**
     * Creates new form GuiAluno
     */
    public GuiAluno(ArrayList<Pessoa> alunos){
        initComponents();
        
        this.cadInstrutorAluno = alunos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpf = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        fTxtCpf = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        fTxtRg = new javax.swing.JFormattedTextField();
        lblEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        lblEscolaridade = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblTelRes = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        fTxtDataNascimento = new javax.swing.JFormattedTextField();
        jComboBoxEscolaridade = new javax.swing.JComboBox<>();
        fTxtCep = new javax.swing.JFormattedTextField();
        fTxtTelRes = new javax.swing.JFormattedTextField();
        fTxtCelular = new javax.swing.JFormattedTextField();
        fTxtNumero = new javax.swing.JFormattedTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        jComboBoxEstadoCIvil = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Aluno");
        setResizable(false);

        lblCpf.setText("CPF");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        lblSexo.setText("Sexo");

        lblEndereco.setText("Endereço");

        lblBairro.setText("Bairro");

        lblCidade.setText("Cidade");

        lblRg.setText("RG");

        lblEmail.setText("Email");

        try {
            fTxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNome.setEnabled(false);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fem", "Masc" }));
        jComboBoxSexo.setEnabled(false);

        txtEndereco.setEnabled(false);

        txtBairro.setEnabled(false);

        txtCidade.setEnabled(false);

        try {
            fTxtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtRg.setEnabled(false);

        lblEstado.setText("Estado");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF", "" }));
        jComboBoxEstado.setEnabled(false);

        txtEmail.setEnabled(false);

        lblDataNascimento.setText("Data Nascimento");

        lblEscolaridade.setText("Escolaridade");

        lblNumero.setText("Nº");

        lblCep.setText("CEP");

        lblTelRes.setText("Tel. Res");

        lblCelular.setText("Celular");

        fTxtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fTxtDataNascimento.setText(" / /");
        fTxtDataNascimento.setToolTipText("");
        fTxtDataNascimento.setEnabled(false);

        jComboBoxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Educação infantil", "Fundamental", "Médio", "Superior (Graduação)", "Pós-graduação", "Mestrado", "Doutorado", "Escola" }));
        jComboBoxEscolaridade.setEnabled(false);

        try {
            fTxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtCep.setEnabled(false);

        try {
            fTxtTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtTelRes.setEnabled(false);

        try {
            fTxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtCelular.setEnabled(false);

        fTxtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fTxtNumero.setEnabled(false);

        lblEstadoCivil.setText("Estado Civil");

        jComboBoxEstadoCIvil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Solteiro" }));
        jComboBoxEstadoCIvil.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSexo)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnConsultar)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnInserir)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnAlterar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmail)
                                            .addComponent(lblRg))
                                        .addGap(26, 26, 26)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, Short.MAX_VALUE)
                                .addComponent(btnExcluir)
                                .addGap(36, 36, 36)
                                .addComponent(btnSair))
                            .addComponent(lblCpf)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNumero)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblNome)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(58, 58, 58)
                                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblEstadoCivil)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jComboBoxEstadoCIvil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(34, 34, 34)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblDataNascimento)
                                                .addComponent(lblEscolaridade)))
                                        .addComponent(lblCep))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fTxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCidade)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lblEstado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTelRes))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(282, 282, 282)
                                                .addComponent(lblCelular)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fTxtTelRes, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(fTxtCep)
                                    .addComponent(fTxtCelular)
                                    .addComponent(fTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fTxtDataNascimento)
                                    .addComponent(jComboBoxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(fTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascimento)
                    .addComponent(fTxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEscolaridade)
                    .addComponent(jComboBoxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoCivil)
                    .addComponent(jComboBoxEstadoCIvil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero)
                    .addComponent(fTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCep)
                    .addComponent(fTxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelRes)
                    .addComponent(fTxtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRg)
                    .addComponent(fTxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular)
                    .addComponent(fTxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if(!Pessoa.validarCpf(fTxtCpf.getText())){
            javax.swing.JOptionPane.showMessageDialog(null,"CPF INVÁLIDO, tente outro");
            fTxtCpf.setText("");
            fTxtCpf.requestFocus();
            return;
        }
        
        alunoAtual = -1;
        
        for (int index= 0; index < cadInstrutorAluno.size(); index ++){
            if (cadInstrutorAluno.get(index) instanceof Aluno){
                if (cadInstrutorAluno.get(index).getCpf().equals(fTxtCpf.getText().replace(".", "").replace("-", ""))){
                    alunoAtual = index;
                }
            }
        }
        
        if(alunoAtual == -1){
            habilitarInsercao();
            return;
        }
            
        habilitarEdicao();
            
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        Aluno aluno = new Aluno(fTxtCpf.getText().replace(".", "").replace("-", ""), txtNome.getText());
        aluno.setBairro(txtBairro.getText());
        aluno.setCelular(fTxtCelular.getText().replace("(", "").replace(")", "").replace("-", ""));
        aluno.setCep(fTxtCep.getText());
        aluno.setCidade(txtCidade.getText());
        aluno.setEmail(txtEmail.getText());
        aluno.setEndereco(txtEndereco.getText());
        aluno.setEstado(jComboBoxEstado.getSelectedItem().toString());
        aluno.setTelefone(fTxtTelRes.getText().replace("(", "").replace(")", "").replace("-", ""));
        aluno.setRg(fTxtRg.getText().replace(".", "").replace("-", ""));
        aluno.setSexo(jComboBoxSexo.getSelectedItem().toString());
        aluno.setNumero(Integer.parseInt(fTxtNumero.getText()));
        aluno.setEscolaridade(jComboBoxEscolaridade.getSelectedItem().toString());
        aluno.setDataNasc(fTxtDataNascimento.getText());
        aluno.setEstadoCivil(jComboBoxEstadoCIvil.getSelectedItem().toString());
        
        cadInstrutorAluno.add(aluno);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Aluno aluno = (Aluno)cadInstrutorAluno.get(alunoAtual);
        
        // Atualizando
        aluno.setNome(txtNome.getText());
        aluno.setBairro(txtBairro.getText());
        aluno.setCelular(fTxtCelular.getText().replace("(", "").replace(")", "").replace("-", ""));
        aluno.setCep(fTxtCep.getText());
        aluno.setCidade(txtCidade.getText());
        aluno.setEmail(txtEmail.getText());
        aluno.setEndereco(txtEndereco.getText());
        aluno.setEstado(jComboBoxEstado.getSelectedItem().toString());
        aluno.setTelefone(fTxtTelRes.getText().replace("(", "").replace(")", "").replace("-", ""));
        aluno.setRg(fTxtRg.getText().replace(".", "").replace("-", ""));
        aluno.setSexo(jComboBoxSexo.getSelectedItem().toString());
        aluno.setNumero(Integer.parseInt(fTxtNumero.getText()));
        aluno.setEscolaridade(jComboBoxEscolaridade.getSelectedItem().toString());
        aluno.setDataNasc(fTxtDataNascimento.getText());
        aluno.setEstadoCivil(jComboBoxEstadoCIvil.getSelectedItem().toString());
        
        habilitarConsulta();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        cadInstrutorAluno.remove(alunoAtual);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnExcluirActionPerformed

     private void habilitarEdicao(){
        // Text
        fTxtCpf.setEnabled(false);
        
        fTxtCep.setEnabled(true);
        fTxtCelular.setEnabled(true);
        fTxtRg.setEnabled(true);
        fTxtTelRes.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNome.setEnabled(true);
        fTxtNumero.setEnabled(true);
        fTxtDataNascimento.setEnabled(true);
        
        // ComboBox
        jComboBoxEstado.setEnabled(true);
        jComboBoxEscolaridade.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxEstadoCIvil.setEnabled(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(true);
        
        // Deixando o aluno atual visível
        Aluno aluno = (Aluno)cadInstrutorAluno.get(alunoAtual);
        // dados Text
        fTxtCpf.setText(aluno.getCpf());
        
        fTxtCelular.setText(aluno.getCelular());
        fTxtCep.setText(aluno.getCep());
        fTxtRg.setText(aluno.getRg());
        fTxtTelRes.setText(aluno.getTelefone());
        txtBairro.setText(aluno.getBairro());
        txtCidade.setText(aluno.getCidade());
        txtEmail.setText(aluno.getEmail());
        txtEndereco.setText(aluno.getEndereco());
        txtNome.setText(aluno.getNome());
        fTxtNumero.setText(String.valueOf(aluno.getNumero()));
        fTxtDataNascimento.setText(aluno.getDataNasc());
        
        // dados ComboBox
        jComboBoxEstado.setSelectedItem(aluno.getEstado());
        jComboBoxEscolaridade.setSelectedItem(aluno.getEscolaridade());
        jComboBoxSexo.setSelectedItem(aluno.getSexo());
        jComboBoxEstadoCIvil.setSelectedItem(aluno.getEstadoCivil());
        
        // Focus
        txtNome.requestFocus();
    }
    
    private void habilitarInsercao(){
        // Text
        fTxtCpf.setEnabled(false);
        
        fTxtCelular.setEnabled(true);
        fTxtCep.setEnabled(true);
        fTxtRg.setEnabled(true);
        fTxtTelRes.setEnabled(true);
        fTxtDataNascimento.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNome.setEnabled(true);
        fTxtNumero.setEnabled(true);
        
        // ComboBox
        jComboBoxEstado.setEnabled(true);
        jComboBoxEscolaridade.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxEstadoCIvil.setEnabled(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(true);
        btnExcluir.setEnabled(false);
        
        // Focus
        txtNome.requestFocus();
    }
    
    private void habilitarConsulta(){
        // Text
        fTxtCpf.setEnabled(true);
        
        fTxtCelular.setEnabled(false);
        fTxtCep.setEnabled(false);
        fTxtRg.setEnabled(false);
        fTxtTelRes.setEnabled(false);
        fTxtDataNascimento.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCidade.setEnabled(false);
        txtEmail.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNome.setEnabled(false);
        fTxtNumero.setEnabled(false);
        
        // ComboBox
        jComboBoxEstado.setEnabled(false);
        jComboBoxEscolaridade.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jComboBoxEstadoCIvil.setEnabled(false);
        
        // Botões
        btnConsultar.setEnabled(true);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Zerando Text
        fTxtCpf.setText("");
        
        fTxtCelular.setText("");
        fTxtCep.setText("");
        fTxtRg.setText("");
        fTxtTelRes.setText("");
        fTxtDataNascimento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtNome.setText("");
        fTxtNumero.setText("");
        
        // Zerando ComboBox
        jComboBoxEstado.setSelectedIndex(0);
        jComboBoxEscolaridade.setSelectedIndex(0);
        jComboBoxSexo.setSelectedIndex(0);
        jComboBoxEstadoCIvil.setSelectedIndex(0);
        
        // Focus
        fTxtCpf.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField fTxtCelular;
    private javax.swing.JFormattedTextField fTxtCep;
    private javax.swing.JFormattedTextField fTxtCpf;
    private javax.swing.JFormattedTextField fTxtDataNascimento;
    private javax.swing.JFormattedTextField fTxtNumero;
    private javax.swing.JFormattedTextField fTxtRg;
    private javax.swing.JFormattedTextField fTxtTelRes;
    private javax.swing.JComboBox<String> jComboBoxEscolaridade;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxEstadoCIvil;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEscolaridade;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelRes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadInstrutorAluno;
    private int alunoAtual;
}
