/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Curso;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author Bley
 */
public class GuiCurso extends javax.swing.JFrame {
    /**
     * Creates new form GuiCursa
     */
    public GuiCurso(ArrayList<Curso> cursos) {
        initComponents();
    
        this.cadCursos = cursos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSiglaCurso = new javax.swing.JLabel();
        lblNomeCurso = new javax.swing.JLabel();
        lblCargaHoraria = new javax.swing.JLabel();
        lblValorCurso = new javax.swing.JLabel();
        lblProgramaCurso = new javax.swing.JLabel();
        txtSiglaCurso = new javax.swing.JTextField();
        txtNomeCurso = new javax.swing.JTextField();
        txtProgramaCurso = new javax.swing.JTextField();
        lblDataVigencia = new javax.swing.JLabel();
        lblValorHoraInstrutor = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        fTxtDataVigencia = new javax.swing.JFormattedTextField();
        fTxtValorHoraInstrutor = new javax.swing.JFormattedTextField();
        fTxtValorCurso = new javax.swing.JFormattedTextField();
        fTxtCargaHoraria = new javax.swing.JFormattedTextField();
        panelTipo = new javax.swing.JPanel();
        radioButtonPresencial = new javax.swing.JRadioButton();
        radioButtonOnline = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Curso");
        setResizable(false);

        lblSiglaCurso.setText("Sigla Curso");

        lblNomeCurso.setText("Nome Curso");

        lblCargaHoraria.setText("Carga horária");

        lblValorCurso.setText("Valor Curso");

        lblProgramaCurso.setText("Programa do Curso");

        txtNomeCurso.setEnabled(false);

        txtProgramaCurso.setEnabled(false);

        lblDataVigencia.setText("Data de vigência");

        lblValorHoraInstrutor.setText("Valor hora instrutor");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        fTxtDataVigencia.setColumns(6);
        fTxtDataVigencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fTxtDataVigencia.setText(" / /");
        fTxtDataVigencia.setEnabled(false);

        fTxtValorHoraInstrutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        fTxtValorHoraInstrutor.setEnabled(false);

        fTxtValorCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        fTxtValorCurso.setEnabled(false);

        fTxtCargaHoraria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fTxtCargaHoraria.setEnabled(false);

        panelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        panelTipo.setToolTipText("");

        radioButtonPresencial.setText("Presencial");
        radioButtonPresencial.setEnabled(false);
        radioButtonPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonPresencialActionPerformed(evt);
            }
        });

        radioButtonOnline.setText("Online");
        radioButtonOnline.setEnabled(false);
        radioButtonOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOnlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTipoLayout = new javax.swing.GroupLayout(panelTipo);
        panelTipo.setLayout(panelTipoLayout);
        panelTipoLayout.setHorizontalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonPresencial)
                    .addComponent(radioButtonOnline))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelTipoLayout.setVerticalGroup(
            panelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonPresencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(radioButtonOnline))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSiglaCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomeCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCargaHoraria, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValorCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProgramaCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fTxtCargaHoraria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(fTxtValorCurso, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataVigencia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorHoraInstrutor, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fTxtDataVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fTxtValorHoraInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProgramaCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtNomeCurso)
                                    .addComponent(txtSiglaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(165, 165, 165)
                                .addComponent(panelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(36, 36, 36)
                        .addComponent(btnInserir)
                        .addGap(36, 36, 36)
                        .addComponent(btnAlterar)
                        .addGap(36, 36, 36)
                        .addComponent(btnExcluir)
                        .addGap(36, 36, 36)
                        .addComponent(btnSair)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSiglaCurso)
                            .addComponent(txtSiglaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeCurso)
                            .addComponent(txtNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCargaHoraria)
                            .addComponent(fTxtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorCurso)
                            .addComponent(fTxtValorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(panelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataVigencia)
                            .addComponent(fTxtDataVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorHoraInstrutor)
                            .addComponent(fTxtValorHoraInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramaCurso)
                    .addComponent(txtProgramaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(34, 34, 34))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        panelTipo.getAccessibleContext().setAccessibleName("Tipo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        txtSiglaCurso.setText(txtSiglaCurso.getText().toUpperCase());
        
        // Caso não tenha nada escrito é retornado
        if(txtSiglaCurso.getText().length() < 1)
            return;
        
        atualCurso = -1;
        
        for (int index = 0; index < cadCursos.size(); index++){
            if(txtSiglaCurso.getText().equals(cadCursos.get(index).getSigla()))
                atualCurso = index;
        }
        
        if(atualCurso < 0){
            habilitarInsercao();
            return;
        }
        
        habilitarEdicao();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        
        Curso curso = new Curso(txtSiglaCurso.getText(), txtNomeCurso.getText());
        curso.setCargaHorario(Integer.parseInt(fTxtCargaHoraria.getText()));
        curso.setDataVigencia(fTxtDataVigencia.getText());
        curso.setPrograma(txtProgramaCurso.getText());
        curso.setValor(Double.parseDouble(fTxtValorCurso.getText().replace(",", ".")));
        curso.setValorHoraInstrutor(Double.parseDouble(fTxtValorHoraInstrutor.getText().replace(",", ".")));
        
        // Tipo
        if(radioButtonOnline.isSelected()){
            curso.setTipo("Presencial");
        }else{
            curso.setTipo("Online");
        }
        
        cadCursos.add(curso);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Curso curso = cadCursos.get(atualCurso);
        curso.setNome(txtNomeCurso.getText());
        curso.setCargaHorario(Integer.parseInt(fTxtCargaHoraria.getText()));
        curso.setDataVigencia(fTxtDataVigencia.getText());
        curso.setPrograma(txtProgramaCurso.getText());
        curso.setValor(Double.parseDouble(fTxtValorCurso.getText().replace(",", ".")));
        curso.setValorHoraInstrutor(Double.parseDouble(fTxtValorHoraInstrutor.getText().replace(",", ".")));
        
        // Tipo
        if(radioButtonPresencial.isSelected()){
            curso.setTipo("Presencial");
        }else{
            curso.setTipo("Online");
        }
        
        habilitarConsulta();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        cadCursos.remove(atualCurso);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void radioButtonPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonPresencialActionPerformed
        if (radioButtonPresencial.isSelected()){
            radioButtonOnline.setSelected(false);
        }
    }//GEN-LAST:event_radioButtonPresencialActionPerformed

    private void radioButtonOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonOnlineActionPerformed
        if (radioButtonOnline.isSelected()){
            radioButtonPresencial.setSelected(false);
        }
    }//GEN-LAST:event_radioButtonOnlineActionPerformed

    private void habilitarEdicao(){
        // Text
        txtSiglaCurso.setEnabled(false);
        
        fTxtValorHoraInstrutor.setEnabled(true);
        fTxtCargaHoraria.setEnabled(true);
        txtNomeCurso.setEnabled(true);
        txtProgramaCurso.setEnabled(true);
        fTxtValorCurso.setEnabled(true);
        fTxtDataVigencia.setEnabled(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(true);
        
        // radiobutton
        radioButtonOnline.setEnabled(true);
        radioButtonPresencial.setEnabled(true);
        
        // Deixando o curso atual visível
        Curso curso = cadCursos.get(atualCurso);
        fTxtValorHoraInstrutor.setText(Double.toString(curso.getValorHoraInstrutor()));
        fTxtCargaHoraria.setText(Integer.toString(curso.getCargaHorario()));
        txtNomeCurso.setText(curso.getNome());
        txtProgramaCurso.setText(curso.getPrograma());
        fTxtValorCurso.setText(Double.toString(curso.getValor()));
        fTxtDataVigencia.setText(curso.getDataVigencia());
        
        if(curso.getTipo().equals("Presencial")){
            radioButtonPresencial.setSelected(true);
        }else{
            radioButtonOnline.setSelected(true);
        }
        
        // Focus
        txtNomeCurso.requestFocus();
    }
    
    private void habilitarInsercao(){
        // Text
        txtSiglaCurso.setEnabled(false);
        
        fTxtValorHoraInstrutor.setEnabled(true);
        fTxtCargaHoraria.setEnabled(true);
        txtNomeCurso.setEnabled(true);
        txtProgramaCurso.setEnabled(true);
        fTxtValorCurso.setEnabled(true);
        fTxtDataVigencia.setEnabled(true);
        
        // radiobutton
        radioButtonOnline.setEnabled(true);
        radioButtonPresencial.setEnabled(true);
        radioButtonPresencial.setSelected(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(true);
        btnExcluir.setEnabled(false);
        
        // Focus
        txtNomeCurso.requestFocus();
    }
    
    private void habilitarConsulta(){
        // Text
        txtSiglaCurso.setEnabled(true);
        
        fTxtValorHoraInstrutor.setEnabled(false);
        fTxtCargaHoraria.setEnabled(false);
        txtNomeCurso.setEnabled(false);
        txtProgramaCurso.setEnabled(false);
        fTxtValorCurso.setEnabled(false);
        fTxtDataVigencia.setEnabled(false);
        
        // Botões
        btnConsultar.setEnabled(true);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // radiobutton
        radioButtonOnline.setEnabled(false);
        radioButtonPresencial.setEnabled(false);
        
        // Zerando Text
        txtSiglaCurso.setText("");
        fTxtValorHoraInstrutor.setText("");
        fTxtCargaHoraria.setText("");
        txtNomeCurso.setText("");
        txtProgramaCurso.setText("");
        fTxtValorCurso.setText("");
        fTxtDataVigencia.setText("");
        
        // Zerando radiobutton
        radioButtonOnline.setSelected(false);
        radioButtonPresencial.setSelected(false);
        
        // Focus
        txtSiglaCurso.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField fTxtCargaHoraria;
    private javax.swing.JFormattedTextField fTxtDataVigencia;
    private javax.swing.JFormattedTextField fTxtValorCurso;
    private javax.swing.JFormattedTextField fTxtValorHoraInstrutor;
    private javax.swing.JLabel lblCargaHoraria;
    private javax.swing.JLabel lblDataVigencia;
    private javax.swing.JLabel lblNomeCurso;
    private javax.swing.JLabel lblProgramaCurso;
    private javax.swing.JLabel lblSiglaCurso;
    private javax.swing.JLabel lblValorCurso;
    private javax.swing.JLabel lblValorHoraInstrutor;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JRadioButton radioButtonOnline;
    private javax.swing.JRadioButton radioButtonPresencial;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtProgramaCurso;
    private javax.swing.JTextField txtSiglaCurso;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Curso> cadCursos;
    private int atualCurso;
}
