/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Instrutor;
import fatec.poo.model.Pessoa;
import java.beans.Introspector;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bley
 */
public class GuiInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form GuiCadastroCondutor
     */
    public GuiInstrutor(ArrayList<Pessoa> instrutores){
        initComponents();
        
        this.cadInstrutorAluno = instrutores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        fTxtCpf = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        fTxtRg = new javax.swing.JFormattedTextField();
        lblCpf = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblDataNascimento = new javax.swing.JLabel();
        fTxtDataNasc = new javax.swing.JFormattedTextField();
        lblNumero = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblTelRes = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        fTxtCep = new javax.swing.JFormattedTextField();
        fTxtTelRes = new javax.swing.JFormattedTextField();
        fTxtCelular = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxEstadoCivil = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAreaAtuacao = new javax.swing.JTextField();
        lblFormacao = new javax.swing.JLabel();
        txtFormacao = new javax.swing.JTextField();
        fTxtNumero = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Instrutor");
        setResizable(false);

        lblNome.setText("Nome");

        lblSexo.setText("Sexo");

        lblEndereco.setText("Endereço");

        lblBairro.setText("Bairro");

        lblCidade.setText("Cidade");

        lblRg.setText("RG");

        lblEmail.setText("Email");

        try {
            fTxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtNome.setEnabled(false);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fem", "Masc" }));
        jComboBoxSexo.setEnabled(false);

        txtEndereco.setEnabled(false);

        txtBairro.setEnabled(false);

        txtCidade.setEnabled(false);

        try {
            fTxtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtRg.setEnabled(false);

        lblCpf.setText("CPF");

        lblEstado.setText("Estado");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF", "" }));
        jComboBoxEstado.setEnabled(false);

        txtEmail.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblDataNascimento.setText("Data Nascimento");

        fTxtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fTxtDataNasc.setText(" / /");
        fTxtDataNasc.setToolTipText("");
        fTxtDataNasc.setEnabled(false);

        lblNumero.setText("Nº");

        lblCep.setText("CEP");

        lblTelRes.setText("Tel. Res");

        lblCelular.setText("Celular");

        try {
            fTxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtCep.setEnabled(false);

        try {
            fTxtTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtTelRes.setEnabled(false);

        try {
            fTxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTxtCelular.setEnabled(false);

        jLabel1.setText("Estado Civil");

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Solteiro" }));
        jComboBoxEstadoCivil.setEnabled(false);

        jLabel2.setText("Area de Atuação");

        txtAreaAtuacao.setEnabled(false);

        lblFormacao.setText("Formacao");

        txtFormacao.setEnabled(false);

        fTxtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fTxtNumero.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(36, 36, 36)
                        .addComponent(btnInserir)
                        .addGap(36, 36, 36)
                        .addComponent(btnAlterar)
                        .addGap(36, 36, 36)
                        .addComponent(btnExcluir)
                        .addGap(36, 36, 36)
                        .addComponent(btnSair))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFormacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCidade)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(116, 116, 116)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCpf)
                                        .addComponent(lblRg)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblSexo)
                                                    .addGap(30, 30, 30))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblBairro)
                                                    .addGap(24, 24, 24))
                                                .addComponent(lblEndereco, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(41, 41, 41)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDataNascimento)
                                    .addGap(18, 18, 18)
                                    .addComponent(fTxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(lblCelular)
                                        .addComponent(lblTelRes)
                                        .addComponent(lblCep)
                                        .addComponent(lblNumero))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fTxtTelRes, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                        .addComponent(fTxtCep)
                                        .addComponent(fTxtCelular)
                                        .addComponent(fTxtNumero)
                                        .addComponent(jComboBoxEstadoCivil, 0, 91, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fTxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataNascimento)
                                    .addComponent(fTxtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumero)
                                    .addComponent(fTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCep)
                                    .addComponent(fTxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelRes)
                                    .addComponent(fTxtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCelular)
                                    .addComponent(fTxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCpf)
                                    .addComponent(fTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNome)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSexo)
                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEndereco)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBairro)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCidade)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEstado)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRg)
                                    .addComponent(fTxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormacao)
                            .addComponent(txtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        
        if(!Pessoa.validarCpf(fTxtCpf.getText())){
            javax.swing.JOptionPane.showMessageDialog(null,"CPF INVÁLIDO, tente outro");
            fTxtCpf.setText("");
            fTxtCpf.requestFocus();
            return;
        }
        
        instrutorAtual = -1;
        
        for (int index= 0; index < cadInstrutorAluno.size(); index ++){
            if (cadInstrutorAluno.get(index) instanceof Instrutor){
                if (cadInstrutorAluno.get(index).getCpf().equals(fTxtCpf.getText().replace(".", "").replace("-", ""))){
                    instrutorAtual = index;
                }
            }
        }
        
        if(instrutorAtual == -1){
            habilitarInsercao();
            return;
        }
            
        habilitarEdicao();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        
        Instrutor instrutor = new Instrutor(fTxtCpf.getText().replace(".", "").replace("-", ""), txtNome.getText());
        instrutor.setAreaAtuacao(txtAreaAtuacao.getText());
        instrutor.setBairro(txtBairro.getText());
        instrutor.setCelular(fTxtCelular.getText().replace("(", "").replace(")", "").replace("-", ""));
        instrutor.setCep(fTxtCep.getText());
        instrutor.setCidade(txtCidade.getText());
        instrutor.setDataNasc(fTxtDataNasc.getText());
        instrutor.setEmail(txtEmail.getText());
        instrutor.setEndereco(txtEndereco.getText());
        instrutor.setEstado(jComboBoxEstado.getSelectedItem().toString());
        instrutor.setEstadoCivil(jComboBoxEstadoCivil.getSelectedItem().toString());
        instrutor.setAreaAtuacao(txtAreaAtuacao.getText());
        instrutor.setFormacao(txtFormacao.getText());
        instrutor.setTelefone(fTxtTelRes.getText().replace("(", "").replace(")", "").replace("-", ""));
        instrutor.setRg(fTxtRg.getText().replace(".", "").replace("-", ""));
        instrutor.setSexo(jComboBoxSexo.getSelectedItem().toString());
        instrutor.setNumero(Integer.parseInt(fTxtNumero.getText()));
        
        cadInstrutorAluno.add(instrutor);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        Instrutor instrutor = (Instrutor)cadInstrutorAluno.get(instrutorAtual);
        
        // Atualizando
        instrutor.setNome(txtNome.getText());
        instrutor.setAreaAtuacao(txtAreaAtuacao.getText());
        instrutor.setBairro(txtBairro.getText());
        instrutor.setCelular(fTxtCelular.getText().replace("(", "").replace(")", "").replace("-", ""));
        instrutor.setCep(fTxtCep.getText());
        instrutor.setCidade(txtCidade.getText());
        instrutor.setDataNasc(fTxtDataNasc.getText());
        instrutor.setEmail(txtEmail.getText());
        instrutor.setEndereco(txtEndereco.getText());
        instrutor.setEstado(jComboBoxEstado.getSelectedItem().toString());
        instrutor.setEstadoCivil(jComboBoxEstadoCivil.getSelectedItem().toString());
        instrutor.setAreaAtuacao(txtAreaAtuacao.getText());
        instrutor.setFormacao(txtFormacao.getText());
        instrutor.setTelefone(fTxtTelRes.getText().replace("(", "").replace(")", "").replace("-", ""));
        instrutor.setRg(fTxtRg.getText().replace(".", "").replace("-", ""));
        instrutor.setSexo(jComboBoxSexo.getSelectedItem().toString());
        instrutor.setNumero(Integer.parseInt(fTxtNumero.getText()));
        
        habilitarConsulta();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        cadInstrutorAluno.remove(instrutorAtual);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void habilitarEdicao(){
        // Text
        fTxtCpf.setEnabled(false);
        
        fTxtCep.setEnabled(true);
        fTxtCelular.setEnabled(true);
        fTxtRg.setEnabled(true);
        fTxtTelRes.setEnabled(true);
        fTxtDataNasc.setEnabled(true);
        txtAreaAtuacao.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNome.setEnabled(true);
        fTxtNumero.setEnabled(true);
        txtFormacao.setEnabled(true);
        
        // ComboBox
        jComboBoxEstado.setEnabled(true);
        jComboBoxEstadoCivil.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(true);
        
        // Deixando o instrutor atual visível
        Instrutor instrutor = (Instrutor)cadInstrutorAluno.get(instrutorAtual);
        // dados Text
        fTxtCpf.setText(instrutor.getCpf());
        
        fTxtCelular.setText(instrutor.getCelular());
        fTxtCep.setText(instrutor.getCep());
        fTxtRg.setText(instrutor.getRg());
        fTxtDataNasc.setText(instrutor.getDataNasc());
        fTxtTelRes.setText(instrutor.getTelefone());
        txtAreaAtuacao.setText(instrutor.getAreaAtuacao());
        txtBairro.setText(instrutor.getBairro());
        txtCidade.setText(instrutor.getCidade());
        txtEmail.setText(instrutor.getEmail());
        txtEndereco.setText(instrutor.getEndereco());
        txtNome.setText(instrutor.getNome());
        fTxtNumero.setText(String.valueOf(instrutor.getNumero()));
        txtFormacao.setText(instrutor.getFormacao());
        
        // dados ComboBox
        jComboBoxEstado.setSelectedItem(instrutor.getEstado());
        jComboBoxEstadoCivil.setSelectedItem(instrutor.getEstadoCivil());
        jComboBoxSexo.setSelectedItem(instrutor.getSexo());
        
        // Focus
        txtNome.requestFocus();
    }
    
    private void habilitarInsercao(){
        // Text
        fTxtCpf.setEnabled(false);
        
        fTxtCelular.setEnabled(true);
        fTxtCep.setEnabled(true);
        fTxtRg.setEnabled(true);
        fTxtTelRes.setEnabled(true);
        fTxtDataNasc.setEnabled(true);
        txtAreaAtuacao.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEmail.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNome.setEnabled(true);
        fTxtNumero.setEnabled(true);
        txtFormacao.setEnabled(true);
        
        // ComboBox
        jComboBoxEstado.setEnabled(true);
        jComboBoxEstadoCivil.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(true);
        btnExcluir.setEnabled(false);
        
        // Focus
        txtNome.requestFocus();
    }
    
    private void habilitarConsulta(){
        // Text
        fTxtCpf.setEnabled(true);
        
        fTxtCelular.setEnabled(false);
        fTxtCep.setEnabled(false);
        fTxtRg.setEnabled(false);
        fTxtDataNasc.setEnabled(false);
        fTxtTelRes.setEnabled(false);
        txtAreaAtuacao.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCidade.setEnabled(false);
        txtEmail.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNome.setEnabled(false);
        fTxtNumero.setEnabled(false);
        txtFormacao.setEnabled(false);
        
        // ComboBox
        jComboBoxEstado.setEnabled(false);
        jComboBoxEstadoCivil.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        
        // Botões
        btnConsultar.setEnabled(true);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Zerando Text
        fTxtCpf.setText("");
        
        fTxtCelular.setText("");
        fTxtCep.setText("");
        fTxtRg.setText("");
        fTxtDataNasc.setText("");
        fTxtTelRes.setText("");
        txtAreaAtuacao.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtNome.setText("");
        fTxtNumero.setText("");
        txtFormacao.setText("");
        
        // Zerando ComboBox
        jComboBoxEstado.setSelectedIndex(0);
        jComboBoxEstadoCivil.setSelectedIndex(0);
        jComboBoxSexo.setSelectedIndex(0);
        
        // Focus
        fTxtCpf.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField fTxtCelular;
    private javax.swing.JFormattedTextField fTxtCep;
    private javax.swing.JFormattedTextField fTxtCpf;
    private javax.swing.JFormattedTextField fTxtDataNasc;
    private javax.swing.JFormattedTextField fTxtNumero;
    private javax.swing.JFormattedTextField fTxtRg;
    private javax.swing.JFormattedTextField fTxtTelRes;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxEstadoCivil;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFormacao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelRes;
    private javax.swing.JTextField txtAreaAtuacao;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFormacao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadInstrutorAluno;
    private int instrutorAtual;
}
