/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Curso;
import fatec.poo.model.Turma;
import java.util.ArrayList;

/**
 *
 * @author Bley
 */
public class GuiTurma extends javax.swing.JFrame {

    /**
     * Creates new form GuiTurma
     */
    public GuiTurma(ArrayList<Turma> turmas, ArrayList<Curso> cursos) {
        initComponents();
        
        this.cadCursos = cursos;
        this.cadTurmas = turmas;
        
        for (Curso curso : cadCursos)
            jComboBoxCurso.addItem(curso.getSigla());
        
        if(jComboBoxCurso.getItemCount() > 0)
            txtSiglaTurma.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fTxtDataInicio = new javax.swing.JFormattedTextField();
        fTxtDataTermino = new javax.swing.JFormattedTextField();
        jComboBoxPeriodo = new javax.swing.JComboBox<>();
        txtSiglaTurma = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        fTxtQtdVagas = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Turma");
        setResizable(false);

        lblCurso.setText("Curso");

        jLabel1.setText("Sigla da turma");

        jLabel2.setText("Nome");

        jLabel3.setText("Qtde vagas");

        jLabel4.setText("Data início");

        jLabel5.setText("Período");
        jLabel5.setEnabled(false);

        jLabel6.setText("Data término");
        jLabel6.setEnabled(false);

        fTxtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fTxtDataInicio.setText(" / / ");
        fTxtDataInicio.setToolTipText("");
        fTxtDataInicio.setEnabled(false);

        fTxtDataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        fTxtDataTermino.setText(" / /");
        fTxtDataTermino.setToolTipText("");
        fTxtDataTermino.setEnabled(false);

        jComboBoxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        jComboBoxPeriodo.setEnabled(false);

        txtSiglaTurma.setEnabled(false);

        txtNome.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        fTxtQtdVagas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fTxtQtdVagas.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(36, 36, 36)
                        .addComponent(btnInserir)
                        .addGap(36, 36, 36)
                        .addComponent(btnAlterar)
                        .addGap(36, 36, 36)
                        .addComponent(btnExcluir)
                        .addGap(36, 36, 36)
                        .addComponent(btnSair)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(lblCurso))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSiglaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fTxtQtdVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fTxtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxPeriodo, 0, 100, Short.MAX_VALUE)
                                            .addComponent(fTxtDataTermino))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSiglaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(fTxtQtdVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(fTxtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fTxtDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBoxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(43, 43, 43))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        
        Turma turma = new Turma(txtSiglaTurma.getText(), "");
        turma.setNomeTurma(txtNome.getText());
        turma.setQtdVagas(Integer.parseInt(fTxtQtdVagas.getText()));
        turma.setDataInicio(fTxtDataInicio.getText());
        turma.setDataTermino(fTxtDataTermino.getText());
        turma.setPeriodo(jComboBoxPeriodo.getSelectedItem().toString());
        
        Curso cursoEscolhido = getCursoComboBox();
        
        cursoEscolhido.addTurma(turma);
        
        cadTurmas.add(turma);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        Turma turma = cadTurmas.get(atualTurma);
        turma.setNomeTurma(txtNome.getText());
        turma.setQtdVagas(Integer.parseInt(fTxtQtdVagas.getText()));
        turma.setDataInicio(fTxtDataInicio.getText());
        turma.setDataTermino(fTxtDataTermino.getText());
        turma.setPeriodo(jComboBoxPeriodo.getSelectedItem().toString());
        
        // Removendo Curso Anterior
        Curso cursoOld = turma.getCurso();
        cursoOld.removeTurma(turma);
        
        // Adicionando curso Atual
        Curso cursoNew = getCursoComboBox();
        cursoNew.addTurma(turma);
        
        habilitarConsulta();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        Turma turma = cadTurmas.get(atualTurma);
        
        Curso cursoEscolhido = getCursoComboBox();
        cursoEscolhido.removeTurma(turma);
        
        cadTurmas.remove(atualTurma);
        habilitarConsulta();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        txtSiglaTurma.setText(txtSiglaTurma.getText().toUpperCase());
        
        // Caso não tenha nada escrito é retornado
        if(txtSiglaTurma.getText().length() < 1)
            return;
        
        atualTurma = -1;
        
        for (int index = 0; index < cadTurmas.size(); index++){
            if(txtSiglaTurma.getText().equals(cadTurmas.get(index).getSiglaTurma()))
                atualTurma = index;
        }
        
        if(atualTurma < 0){
            habilitarInsercao();
            return;
        }
        
        habilitarEdicao();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void habilitarEdicao(){
        // Text
        txtSiglaTurma.setEnabled(false);
        
        txtNome.setEnabled(true);
        fTxtQtdVagas.setEnabled(true);
        fTxtDataInicio.setEnabled(true);
        fTxtDataTermino.setEnabled(true);
        
        // ComboBox
        jComboBoxPeriodo.setEnabled(true);
        jComboBoxCurso.setEnabled(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(true);
        
        // Deixando a turma atual visível
        Turma turma = cadTurmas.get(atualTurma);
        
        // dados Text
        txtNome.setText(turma.getNomeTurma());
        fTxtQtdVagas.setText(String.valueOf(turma.getQtdVagas()));
        fTxtDataInicio.setText(turma.getDataInicio());
        fTxtDataTermino.setText(turma.getDataTermino());
        
        // dados ComboBox
        jComboBoxPeriodo.setSelectedItem(turma.getPeriodo());
        jComboBoxCurso.setSelectedItem(turma.getCurso().getSigla());
        
        // Focus
        txtNome.requestFocus();
    }
    
    private void habilitarInsercao(){
        // Text
        txtSiglaTurma.setEnabled(false);
        
        txtNome.setEnabled(true);
        fTxtQtdVagas.setEnabled(true);
        fTxtDataInicio.setEnabled(true);
        fTxtDataTermino.setEnabled(true);
        
        // ComboBox
        jComboBoxPeriodo.setEnabled(true);
        jComboBoxCurso.setEnabled(true);
        
        // Botões
        btnConsultar.setEnabled(false);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(true);
        btnExcluir.setEnabled(false);
        
        // Focus
        txtNome.requestFocus();
    }
    
    private void habilitarConsulta(){
        // Text
        txtSiglaTurma.setEnabled(true);
        
        txtNome.setEnabled(false);
        fTxtQtdVagas.setEnabled(false);
        fTxtDataInicio.setEnabled(false);
        fTxtDataTermino.setEnabled(false);
        
        // ComboBox
        jComboBoxPeriodo.setEnabled(false);
        jComboBoxCurso.setEnabled(true);

        // Botões
        btnConsultar.setEnabled(true);
        
        btnAlterar.setEnabled(false);
        btnInserir.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Zerando Text
        txtSiglaTurma.setText("");
        txtNome.setText("");
        fTxtQtdVagas.setText("");
        fTxtDataInicio.setText("");
        fTxtDataTermino.setText("");
        
        // Zerando ComboBox
        jComboBoxPeriodo.setSelectedItem(0);
        jComboBoxCurso.setSelectedItem(0);
        
        // Focus
        txtSiglaTurma.requestFocus();
    }
    
    //
    // Método retorna curso atual selecionado em 'jComboBoxCurso'
    //
    private Curso getCursoComboBox(){
        
        Curso cursoEscolhido = null;
        for (Curso curso : cadCursos){
            if(curso.getSigla().equals(jComboBoxCurso.getSelectedItem().toString()))
                cursoEscolhido = curso;
        }
        
        return cursoEscolhido;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField fTxtDataInicio;
    private javax.swing.JFormattedTextField fTxtDataTermino;
    private javax.swing.JFormattedTextField fTxtQtdVagas;
    private javax.swing.JComboBox<String> jComboBoxCurso;
    private javax.swing.JComboBox<String> jComboBoxPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSiglaTurma;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Turma> cadTurmas;
    private ArrayList<Curso> cadCursos;
    private int atualTurma;
}
